export const ERROR_MESSAGE = 'Smth went wrong'

export const FETCH_USERS = 'ghu:/FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'ghu:/FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAIL = 'ghu:/FETCH_USERS_FAIL'

export const FETCH_FOLLOWERS = 'ghu:/FETCH_FOLLOWERS'
export const FETCH_FOLLOWERS_SUCCESS = 'ghu:/FETCH_FOLLOWERS_SUCCESS'
export const FETCH_FOLLOWERS_FAIL = 'ghu:/FETCH_FOLLOWERS_FAIL'
