export const HEADER_MAX_HEIGHT = 200
export const HEADER_MIN_HEIGHT = 60
export const HEADER_SCROLL_DISTANCE = HEADER_MAX_HEIGHT - HEADER_MIN_HEIGHT
export const MAX_LOGIN_FONT_SIZE = 25
export const MIN_LOGIN_FONT_SIZE = 15
